export type ShotDesign = {purpose:string;subject:string;action:string;shot_size:string;camera_angle:string;placement:string;direction:string;composition:string;lighting:string;camera_move:string;narration_excerpt:string};
const blank:ShotDesign={purpose:'',subject:'',action:'',shot_size:'wide',camera_angle:'eye',placement:'center',direction:'left-to-right',composition:'',lighting:'',camera_move:'static',narration_excerpt:''};
const presets=[{label:'Toàn cảnh chếch cao · luồng sông',shot_size:'wide',camera_angle:'high',composition:'River channel with foreground, midground and background',camera_move:'static'},{label:'Máy thấp sát mạn thuyền',shot_size:'medium',camera_angle:'low',composition:'Boat side with clear travel direction',camera_move:'short_follow'},{label:'Trung cảnh qua vai người quan sát',shot_size:'medium',camera_angle:'over_shoulder',composition:'Observer foreground and river beyond',camera_move:'slow_push'},{label:'Đặc tả mái chèo / cọc / dòng nước',shot_size:'detail',camera_angle:'eye',composition:'Historically reviewed detail with clear silhouette',camera_move:'static'}];
const labels:Record<string,string>={purpose:'Mục đích kể chuyện',subject:'Chủ thể',action:'Hành động',placement:'Vị trí chủ thể',direction:'Hướng nhìn / chuyển động',composition:'Bố cục',lighting:'Ánh sáng',narration_excerpt:'Đoạn lời dẫn'};
export default function ShotStoryboard({shots,onChange,duration,narration,images=[],previous=[],original=[],disabled=false}:{shots:ShotDesign[];onChange:(shots:ShotDesign[])=>void;duration?:number;narration:string;images?:string[];previous?:string[];original?:ShotDesign[];disabled?:boolean}){
 const count=duration?Math.ceil(duration/(81/16)):0;
 const update=(i:number,patch:Partial<ShotDesign>)=>onChange(shots.map((s,j)=>j===i?{...s,...patch}:s));
 return <fieldset className="full" disabled={disabled}><legend>Storyboard · góc máy có chủ đích</legend><p>Đoạn lời dẫn được chia gần đúng theo độ dài văn bản, không căn theo timestamp; hãy sửa từng đoạn trước khi duyệt. Không thêm lượt GPU: {count||'chưa đo'} shot theo audio. Đổi góc cần ảnh riêng và duyệt cả bộ trước Wan. Audio và file cũ được giữ; chỉ shot có đầu vào thay đổi cần tạo lại.</p><p>Preset là lựa chọn đạo diễn, không phải chứng cứ vị trí lịch sử. Kiểm tra trục 180°, hướng, ánh sáng, trang phục bằng mắt; chain_last có nguy cơ tích lũy biến dạng.</p>{!shots.length&&<button type="button" disabled={!count} onClick={()=>onChange(Array.from({length:count},(_,i)=>({...blank,narration_excerpt:narration.slice(Math.floor(narration.length*i/count),Math.floor(narration.length*(i+1)/count))})))}>Lập shot list từ audio đã đo</button>}
 {shots.map((s,i)=><section className="panel" key={i}><h3>Shot {i+1} · {JSON.stringify(s)!==JSON.stringify(original[i])?'Cần duyệt thay đổi':'Đã lưu chỉ dẫn'}</h3><div className="review-images">{[previous[i],images[i]].map((id,j)=>id?<figure key={j}><img loading="lazy" src={`/api/studio/artifacts/${id}/file`} alt={`${j?'Hiện tại':'Trước sửa'} · shot ${i+1}`}/><figcaption>{j?'Hiện tại':'Trước sửa'}</figcaption></figure>:null)}</div><label>Preset Bạch Đằng<select value="" onChange={e=>{const preset=presets[Number(e.target.value)];if(preset)update(i,{shot_size:preset.shot_size,camera_angle:preset.camera_angle,composition:preset.composition,camera_move:preset.camera_move});}}><option value="">Chọn góc có chủ đích</option>{presets.map((p,j)=><option key={j} value={j}>{p.label}</option>)}</select></label><div className="form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input value={s[key as keyof ShotDesign]} onChange={e=>update(i,{[key]:e.target.value})}/></label>)}{[['shot_size','Cỡ cảnh',['wide','medium','close','detail']],['camera_angle','Góc máy',['high','eye','low','over_shoulder']],['camera_move','Một chuyển động máy',['static','slow_push','gentle_slide','short_follow']]].map(([key,label,options])=><label key={key as string}>{label}<select value={s[key as keyof ShotDesign]} onChange={e=>update(i,{[key as string]:e.target.value})}>{(options as string[]).map(o=><option key={o}>{o}</option>)}</select></label>)}</div></section>)}<p>Khung dọc: giữ đầu, tay và chi tiết quan trọng trong vùng giữa 80%; chừa 20% dưới cho phụ đề lúc dựng. Không yêu cầu model vẽ chữ.</p></fieldset>;
}
