import { useState } from 'react';
import { api, base, file, type Project, type Run, type Source } from './api';
import { Badge, Field } from './ui';

export function Sources({project:p,run,busy}: {project:Project;run:Run;busy:boolean}) {
  const [role,setRole] = useState('historical');
  return <><div className="section-heading"><div><h2>Thư viện tư liệu</h2><p>Nguồn lịch sử và tham khảo mỹ thuật được lưu riêng. Video được trích khung hình tại máy local.</p></div></div><div className="two-columns"><section className="panel"><h3>Nhập tài liệu hoặc media</h3><Field label="Mục đích"><select value={role} onChange={e => setRole(e.target.value)}><option value="historical">Nguồn lịch sử</option><option value="visual">Tham khảo mỹ thuật</option></select></Field><label className="upload-zone"><strong>＋ Chọn tệp để nhập</strong><span>TXT, PDF có chữ · ảnh · video · nhạc<br/>Tài liệu ≤25 MB · media ≤250 MB</span><input type="file" disabled={busy} accept=".txt,.md,.pdf,.png,.jpg,.jpeg,.webp,.mp4,.mov,.mkv,.webm,.wav,.mp3,.m4a" onChange={e => {const f=e.target.files?.[0]; if(f) void run(async () => {const r=await fetch(`${base}/projects/${p.id}/upload?name=${encodeURIComponent(f.name)}&role=${role}`,{method:'POST',headers:{'content-type':'application/octet-stream'},body:f}); if(!r.ok) throw new Error((await r.json()).detail); return r.json();}); e.target.value='';}}/></label><p className="muted">Ảnh/video luôn là tham khảo mỹ thuật, không tự coi là chứng cứ lịch sử. PDF scan được báo “cần OCR”.</p></section><section className="panel"><h3>Dán một đoạn nguồn</h3><form onSubmit={e => {e.preventDefault(); const form=e.currentTarget; const d=new FormData(form); void run(async () => {await api(`${base}/projects/${p.id}/sources`,{title:d.get('title'),text:d.get('text'),citation:d.get('citation'),role}); form.reset();});}}><Field label="Tên tài liệu"><input name="title" required/></Field><Field label="Nội dung nguyên văn"><textarea name="text" required rows={4}/></Field><Field label="Xuất xứ / đường dẫn / trang"><input name="citation" placeholder="Tác giả, tác phẩm, số trang…"/></Field><button disabled={busy}>Lưu đoạn nguồn</button></form></section></div><div className="source-grid">{p.sources.map(s => <article className="panel source-card" key={s.id}>{['image','frame'].includes(s.kind) && s.artifact_id && <img src={file(s.artifact_id)} alt={s.title}/>}<div className="section-heading"><Badge good={s.role==='historical'}>{s.role==='historical' ? 'Nguồn lịch sử' : 'Mỹ thuật tham khảo'}</Badge><label className="check"><input type="checkbox" checked={s.selected} disabled={busy || s.status==='needs_ocr'} onChange={e => void run(() => api(`${base}/sources/${s.id}`,{selected:e.target.checked,description:s.description},'PATCH'))}/>Sử dụng</label></div><h3>{s.title}</h3>{s.status==='needs_ocr' && <p className="warning-text">PDF scan chưa có lớp chữ. Cần OCR bên ngoài rồi nhập lại; chưa dùng làm nguồn.</p>}{s.status==='partial_text' && <p className="warning-text">Một số trang chưa trích được chữ. Kiểm tra trước khi sử dụng.</p>}{s.text && <details><summary>Xem nội dung nguồn</summary><pre>{s.text}</pre></details>}{s.artifact_id && <a href={file(s.artifact_id)+'?download=true'}>Tải tư liệu gốc ↓</a>}</article>)}</div></>;
}

export function Characters({project:p,run,busy}: {project:Project;run:Run;busy:boolean}) {
  return <><div className="section-heading"><div><h2>Hồ sơ hình ảnh dùng chung</h2><p>Chọn hồ sơ trong từng cảnh để áp dụng mô tả nhân vật, địa điểm và trang phục nhất quán.</p></div></div><section className="panel"><form className="form-grid" onSubmit={e => {e.preventDefault();const form=e.currentTarget;const d=new FormData(form);void run(async () => {await api(`${base}/projects/${p.id}/characters`,{name:d.get('name'),kind:d.get('kind'),description:d.get('description'),reference_ids:d.getAll('reference_ids')});form.reset();});}}><Field label="Tên hồ sơ"><input name="name" required/></Field><Field label="Loại"><select name="kind"><option value="character">Nhân vật</option><option value="location">Bối cảnh / kiến trúc</option><option value="costume">Trang phục / đạo cụ</option></select></Field><div className="full"><Field label="Mô tả đã kiểm chứng"><textarea name="description" required placeholder="Niên đại, vật liệu, màu sắc, hình dáng và chi tiết cần tránh…"/></Field></div><div className="full"><ReferencePicker sources={p.sources}/></div><button disabled={busy} className="primary">Thêm hồ sơ</button></form></section><div className="source-grid">{p.characters.map(c => <article key={c.id} className="panel"><Badge>{c.kind==='character' ? 'Nhân vật' : c.kind==='location' ? 'Bối cảnh' : 'Trang phục'}</Badge><h3>{c.name}</h3><p>{c.description}</p><small>{c.reference_ids.length} ảnh tham chiếu</small></article>)}</div></>;
}

export function ReferencePicker({sources,selected=[]}: {sources:Source[];selected?:string[]}) {return <fieldset><legend>Ảnh tham chiếu đã chọn (tối đa 3)</legend><div className="reference-picker">{sources.filter(s => s.selected && ['image','frame'].includes(s.kind)).map(s => <label key={s.id}><input type="checkbox" name="reference_ids" value={s.id} defaultChecked={selected.includes(s.id)}/>{s.artifact_id && <img src={file(s.artifact_id)} alt=""/>}<span>{s.title}</span></label>)}</div></fieldset>;}
